export const musicArray = [
    {
        artist: 'Falsies',
        album: 'Magenta',
        spotifyUrl: 'https://open.spotify.com/embed/album/7ng2RkZkm2EGoR6c5J4T5i?utm_source=generator',
        production: 'Addl Recording, Mixing, Mastering',
        genres: 'Rock, Indie',
    },
    {
        artist: 'Moodieboy',
        album: 'Better Get Better',
        spotifyUrl: 'https://open.spotify.com/embed/album/6PXRcBsNI5GOFzrNEoIyFb?utm_source=generator',
        production: 'Recording, Mixing',
        genres: 'Pop Punk, Emo',
    },
    {
        artist: 'Anna Bosnick',
        album: 'Fable',
        spotifyUrl: 'https://open.spotify.com/embed/album/3quFrWnOPAekirM0PFCbOZ?utm_source=generator',
        production: 'Mixing',
        genres: 'Instrumental, Folk',
    },
    {
        artist: 'Anna Bosnick',
        album: 'The Ring',
        spotifyUrl: 'https://open.spotify.com/embed/album/72NZaCJQW4XTnbujSKUMBR?utm_source=generator',
        production: 'Recording, Mixing, Mastering',
        genres: 'Folk, Pop, Singer-songwriter',
    },
    {
        artist: 'Charles Warren Orchestra',
        album: 'Moonlanding EP',
        spotifyUrl: 'https://open.spotify.com/embed/album/01si7mk5xOjlYnhlbzAyNR?utm_source=generator',
        production: 'Mixing, Mastering',
        genres: 'Rock, Indie',
    },
    {
        artist: 'Rosa Ingenious',
        album: 'Ghosted',
        spotifyUrl: 'https://open.spotify.com/embed/album/1eJYpbGWOkxR9akqVbOlxy?utm_source=generator',
        production: 'Recording, Mixing, Mastering',
        genres: 'Rock, Brit Rock',
    },
    {
        artist: 'West Side Waltz',
        album: 'Love & Fear',
        spotifyUrl: 'https://open.spotify.com/embed/album/0yClJi5jqn3GPPYkcNa80L?utm_source=generator',
        production: 'Assistant Recording, Mixing, Mastering',
        genres: 'Rock, Folk, Pop',
    },
    {
        artist: 'Lost Martian',
        album: 'Cosmic Humor',
        spotifyUrl: 'https://open.spotify.com/embed/album/1doahEDXdqvQpCWC0CDjcP?utm_source=generator',
        production: 'Recording, Mixing, Mastering',
        genres: 'Pop Punk, Indie',
    },
    {
        artist: 'Ascension TD Christian',
        album: 'Voice to Heaven',
        spotifyUrl: 'https://open.spotify.com/embed/album/5M4lt6PJvmHQpdztuLg8A3?utm_source=generator',
        production: 'Recording, Mixing, Mastering',
        genres: 'Christian, Rock',
    },

]